"""empty message

Revision ID: ed06324566ee
Revises: 7aaa27c1bf44
Create Date: 2017-12-05 09:34:21.613979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed06324566ee'
down_revision = '7aaa27c1bf44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_detail', sa.Column('logo', sa.String(length=256), nullable=False))
    op.add_column('company_detail', sa.Column('site', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_detail', 'site')
    op.drop_column('company_detail', 'logo')
    # ### end Alembic commands ###
