"""empty message

Revision ID: 5f81ad8af0ed
Revises: 70e7047da162
Create Date: 2017-12-05 15:47:52.277969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f81ad8af0ed'
down_revision = '70e7047da162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('description', sa.String(length=1500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'description')
    # ### end Alembic commands ###
