"""empty message

Revision ID: 09efbb09b16c
Revises: 2bba9e4b5891
Create Date: 2017-11-29 14:40:44.969791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09efbb09b16c'
down_revision = '2bba9e4b5891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.String(length=11), nullable=True))
    op.add_column('user', sa.Column('real_name', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('work_years', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'work_years')
    op.drop_column('user', 'real_name')
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###
