"""empty message

Revision ID: 25edb5809e1a
Revises: 09efbb09b16c
Create Date: 2017-11-29 14:56:35.911528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25edb5809e1a'
down_revision = '09efbb09b16c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_detail', 'contact')
    op.drop_column('company_detail', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_detail', sa.Column('email', mysql.VARCHAR(length=24), nullable=False))
    op.add_column('company_detail', sa.Column('contact', mysql.VARCHAR(length=24), nullable=False))
    # ### end Alembic commands ###
