"""empty message

Revision ID: 7aaa27c1bf44
Revises: e7c47626e1be
Create Date: 2017-12-05 09:34:07.366878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7aaa27c1bf44'
down_revision = 'e7c47626e1be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_detail', 'site')
    op.drop_column('company_detail', 'logo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_detail', sa.Column('logo', mysql.VARCHAR(length=64), nullable=False))
    op.add_column('company_detail', sa.Column('site', mysql.VARCHAR(length=64), nullable=False))
    # ### end Alembic commands ###
