"""empty message

Revision ID: e7c47626e1be
Revises: 25edb5809e1a
Create Date: 2017-12-05 09:29:22.171333

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7c47626e1be'
down_revision = '25edb5809e1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_detail', sa.Column('field', sa.String(length=128), nullable=True))
    op.add_column('company_detail', sa.Column('finance_stage', sa.String(length=128), nullable=True))
    op.drop_index('ix_company_detail_slug', table_name='company_detail')
    op.drop_column('company_detail', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_detail', sa.Column('slug', mysql.VARCHAR(length=24), nullable=False))
    op.create_index('ix_company_detail_slug', 'company_detail', ['slug'], unique=True)
    op.drop_column('company_detail', 'finance_stage')
    op.drop_column('company_detail', 'field')
    # ### end Alembic commands ###
