"""empty message

Revision ID: 368dcc662a4e
Revises: 964383c7a3b5
Create Date: 2017-12-05 19:03:15.863450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368dcc662a4e'
down_revision = '964383c7a3b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery', sa.Column('company_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery', 'company_id')
    # ### end Alembic commands ###
