"""order product add price field

Revision ID: 4acf8c290356
Revises: aba0b5f39073
Create Date: 2018-11-20 16:45:26.271275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4acf8c290356'
down_revision = 'aba0b5f39073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_product', sa.Column('price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_product', 'price')
    # ### end Alembic commands ###
